# Jekyll配置文件 - 简化版
title: "AI新闻推送系统"
description: "基于硅基流动AI的智能新闻翻译系统"

# 基本设置
baseurl: ""
url: "https://velist.github.io"

# 完全排除所有Python和开发文件
exclude:
  - "**/*.py"
  - "**/*.pyc"
  - "__pycache__/"
  - "translation/"
  - "old_files/"
  - ".kiro/"
  - "*.log"
  - "requirements.txt"
  - "vercel.json"
  - "deploy.py"
  - "check_deployment.py"
  - "test_*.py"
  - "demo_*.py"
  - "*.md.bak"
  - "任务*.md"
  - "翻译*.md"
  - "硅基流动*.md"
  - "integration_guide.md"
  - "enhanced_news_accumulator.py"
  - "news_accumulator.py"
  - "setup_table_sort.py"
  - "*.bat"
  - "*.msi"
  - "素材/"
  - "archive/"

# 只包含docs目录和必要的文件
include:
  - "docs/"
  - "README.md"

# 禁用插件以避免冲突
plugins: []

# 使用默认主题
theme: minima

# Markdown处理器
markdown: kramdown
highlighter: rouge

# 其他设置
timezone: Asia/Shanghai
encoding: utf-8

# 禁用一些可能导致问题的功能
safe: true
incremental: false